services:
  etendo_ui:
    image: etendo/etendo_ui:0.8.0
    ports:
      - 3000:3000
    networks:
      - etendo
    environment:
      - ETENDO_CLASSIC_URL=${ETENDO_CLASSIC_URL}
      - ETENDO_CLASSIC_HOST=${ETENDO_CLASSIC_HOST}
    extra_hosts:
      - "host.docker.internal:host-gateway"
