services:
  etendo_ui:
    image: etendo/etendo_ui:0.7.0
    ports:
      - 3000:3000
    networks:
      - etendo
    environment:
      - ETENDO_CLASSIC_URL=${ETENDO_CLASSIC_URL}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
